config/routes.rb
CISShoppingCart::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
    
  root :to => "homes#index"
  resources :products, :only => [:index, :show]
  resources :categories, :only => [:index, :show]
  resources :carts, :only => [:show]
  resources :homes, :only => [:index]
  resources :orders
  resources :profiles, :only => [:show]
  namespace :admin do
    root :to => 'dashboards#index'
    resources :dashboards , :only => [:index]
    resources :products, :categories 
    resources  :users ,:only => [:index]  do
      collection do
          post 'block_users'
       end
    end
  end 
  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  has_many :products, :dependent => :destroy
  validates :name, :presence => true
  validates_uniqueness_of :name, :message => '%{value} has already been taken'

  has_many :sub_categories , :dependent => :destroy, :class_name => "Category", :foreign_key => "parent_id" 
  belongs_to :parent, :class_name => "Category"

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	# before_filter :authenticate_admin
	layout 'admin'
	def index
		@categories = Category.where(parent_id: nil).paginate(:page => params[:page], :per_page => 2).search(params[:search])
	end
	def new
		@category = Category.new
		@categories = Category.where(parent_id: nil)
	end
	def show
		@category = Category.find(params[:id])
	end
	def edit
		@category = Category.find(params[:id])
		@categories = Category.where(parent_id: nil)
	end
	def create
		@category = Category.new(params[:category])
		@categories = Category.where(parent_id: nil)
		if @category.save
		  redirect_to admin_category_path(@category)
		else
		  render :new
		end 
	end
	def update
		@category = Category.find(params[:id])
		@category.update_attributes(params[:category])
		redirect_to admin_category_path(@category)
	end
	def destroy
		@category = Category.find(params[:id])
		if @category.delete
			redirect_to :action => 'index'
		else
			render 'index'
		end
	end
	def count
		@categories = Product.all
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.where(parent_id: nil).paginate(:page => params[:page], :per_page => 2).search(params[:search])
	end
	def show
		@category = Category.find(params[:id])
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/_edit_form.html.erb
<div style = "margin-left:20px;">
<%= form_for( @category , :url => admin_category_url ) do |f|%>
<ul>
	<% @category.errors.full_messages.each do |error| %>
	<%= error %>
	<% end %>
</ul>

<p>
	<%= f.label :parent%>
	<%= f.select("parent_id", @categories.collect{|p| [ p.name, p.id ] }, {:include_blank => 'Select category'})%>
</p>

<p>
	<%= f.label :name%>
    <%= f.text_area :name , :cols => "50", :rows => "5"%>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>
</div>

app/views/admin/categories/_form.html.erb
<div style = "margin-left:20px;">
<%= form_for( @category , :url => admin_categories_url ) do |f|%>
<ul>
	<% @category.errors.full_messages.each do |error| %>
	<%= error %>
	<% end %>
</ul>

<p>
	<%= f.label :parent%>
	<%= f.select("parent_id", @categories.collect{|p| [ p.name, p.id ] }, {:include_blank => 'Select category'})%>
</p>

<p>
	<%= f.label :name%>
    <%= f.text_area :name , :cols => "50", :rows => "5"%>
</p>
<p>
	<%= f.submit %>
</p>
<% end %>
</div>

app/views/admin/categories/edit.html.erb
<%= render partial: 'edit_form'%>

app/views/admin/categories/edit.js.erb
$('#edit_form').html("<%= escape_javascript(render :partial => 'edit_form') %>");

app/views/admin/categories/index.html.erb
<div style="float: right;">
  <div style = "margin-right:20px">
    <%= form_tag admin_categories_path, :method => 'get' do %>
      <div style = "margin-left:15px;">
        <p>
          <%= text_field_tag :search, params[:search], :placeholder => "search categories" %>
        </p>
        </div>
    <% end %>
  </div>
</div>
<div style = "margin-left:50px;">
<table class="table table-striped">
  <tbody>
    <tr>
      <td>
        <% @categories.each do |category|%>
            <ul>
              <li>
                <p>
                  <%= link_to "#{category.name}", admin_category_path(category) %>
                  <%= link_to 'Destroy', admin_category_path(category), :confirm => 'Are you sure?',:method => :delete, :class => 'btn btn-mini btn-danger'  %>
                  <%= link_to "Edit", edit_admin_category_path(category), :class => 'btn btn-mini',:remote => true %>
                </p>
              </li>
              <ul>
              <% category.sub_categories.each do |sub_category| %>    
                <li>
                  <p>
                    <%= link_to "#{sub_category.name}", admin_category_path(sub_category)%>
                    <%= link_to 'Destroy', admin_category_path(sub_category), :confirm => 'Are you sure?',:method => :delete, :class => 'btn btn-mini btn-danger'  %>
                    <%= link_to "Edit", edit_admin_category_path(category), :class => 'btn btn-mini',:remote => true %>
                  </p> 
                </li>
              <%end%>
              </ul>
            </ul>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
</div><br/>
<div style = "margin-left:250px">
  <%= button_to "Add Category", new_admin_category_path, :id => "open-contacts-dialog-btn",
      :class => "inbox-sf-add-btn tip", :method => :get, :class => 'btn btn-primary'  %>
</div>
<div style = "margin-left:50px;">
  <%= will_paginate @categories%>
</div>

<div id = "edit_form"></div>

app/views/admin/categories/new.html.erb
<%= render partial: 'form'%>

app/views/admin/categories/show.html.erb
<div style = "margin-left:150px">
	<table>
		<h3>Number of Products{<%= @category.products.count %>}</h3>
		<tr>
			<div><font color="#800000"><%= "Category Name: #{@category.name}"%></font></div><br/>
			<% @category.products.each_with_index do |product,index| %>
				<% if (index%3) == 0 %>
		    	<% end %>
				<td style = "border: 1px solid black; padding: 50px;">
					<div><font color="#800000"><%= (product.product_name)%></font></div><br/>
					<% product.pictures.each do |photo| %>
						<div style = "width:100px">
							<%= link_to image_tag(photo.image.url(:small)), admin_product_path(product)%>
						</div>
					<%end%>
					<div><font color="#JJ2350"><%= "Price: #{product.price}"%></font></div>
					<div><%= truncate(product.description, :length => 20, :separator => '...')%></div>
					<div><%= link_to 'Destroy', admin_product_path(product), :confirm => 'Are you sure?',:method => :delete, :class => 'btn btn-mini btn-danger' %>&nbsp;&nbsp;
						<%= link_to "Edit", edit_admin_product_path(product),:remote => true, :class => 'btn btn-mini' %></div>
				</td>
			<%end%>
		</tr>
			<tr>
				<% @category.sub_categories.each do |sub_category|%>
					<% sub_category.products.each_with_index do |product,index| %>
						<% if (index%3) == 0 %>
				    	<% end %>
						<td style = "border: 1px solid black; padding: 50px;">
							<div><font color="#800000"><%= (product.product_name)%></font></div><br/>
							<% product.pictures.each do |photo| %>
								<div style = "width:100px">
									<%= link_to image_tag(photo.image.url(:small)), admin_product_path(product)%>
								</div>
							<%end%>
							<div><font color="#JJ2350"><%= "Price: #{product.price}"%></font></div>
			            	<div><%= truncate(product.description, :length => 20, :separator => '...')%></div>
			            	<div><%= link_to 'Destroy', admin_product_path(product), :confirm => 'Are you sure?',:method => :delete %>&nbsp;&nbsp;
							<%= link_to "Edit", edit_admin_product_path(product),:remote => true %></div>
						</td>
					<%end%>
				<%end%>
			</tr>
	</table>
</div><br/>

<div style = "margin-left:450px">
	<%= button_to "Add Products", new_admin_product_path, :id => "open-contacts-dialog-btn",
      :class => "inbox-sf-add-btn tip", :method => :get, :class => 'btn btn-primary' %>
</div>

<div id = "edit_form">
</div>