config/routes.rb
CISShoppingCart::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
    
  root :to => "homes#index"
  resources :products, :only => [:index, :show]
  resources :categories, :only => [:index, :show]
  resources :carts, :only => [:show]
  resources :homes, :only => [:index]
  resources :orders
  resources :profiles, :only => [:show]
  namespace :admin do
    root :to => 'dashboards#index'
    resources :dashboards , :only => [:index]
    resources :products, :categories 
    resources  :users ,:only => [:index]  do
      collection do
          post 'block_users'
       end
    end
  end 
  
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :price, :description, :category_id, :product_name, :quantity, :pictures_attributes
  
  belongs_to :category

  has_and_belongs_to_many :orders

  has_many :pictures, :as => :resource, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  
  
  validates :price, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => {:greater_than => 0, :less_than => 100}
  validates :description, :presence => true
  validates :product_name, :presence => true
   

     
  def self.search(search)
    if search
      find(:all, :conditions => ['product_name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
	# before_filter :authenticate_admin
	layout 'admin'
	def index
		@products = Product.paginate(:page => params[:page], :per_page => 9).search(params[:search])
	end
	def new
		@categories = Category.all
		@product = Product.new
	end
	def show
		@product = Product.find(params[:id])
	end
	def edit
		@categories = Category.all
		@product = Product.find(params[:id])
	end
	def create
    @categories = Category.where(parent_id: nil)
    @product =  Product.new(params[:product])
    if @product.save
		  redirect_to admin_product_path(@product)
		else
		  render :new
		end 
	end

	def destroy
		@product = Product.find(params[:id])
		if @product.delete
			redirect_to :action => "index"
		else
			render 'index'
		end
	end
	def update
		@categories = Category.where(parent_id: nil)
		@product = Product.find(params[:id])
		if @product.update_attributes(params[:product])
			redirect_to admin_product_path(@product)
		else
      render :action => 'edit'
    end
	end
end


 

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.paginate(:page => params[:page], :per_page => 9)
	end
	def show
		@product = Product.find(params[:id])
	end
	# def new
	# 	@product = Product.new
	# end
	# def create
	# 	@product = Product.new(params[:product])
	# 	if @product.save
	# 		redirect_to @product
	# 	else
	# 		render 'index'
	# 	end
	# end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_edit_form.html.erb
<div style = "margin-left:150px">
<%= nested_form_for([@category,@product], :url => admin_product_url, :html => {:multipart => true}) do |f|%>
  <ul>
  	<% @product.errors.full_messages.each do |error|%>
  	  <%= error %>
  	<% end %>
  </ul>

  <p>
    <%= f.label :category %>
    <%= f.select :category_id , options_for_select(@categories.map{|c| [c.name , c.id]})  %>
  </p>

  <p class="tag">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </p>

  <%= f.fields_for :pictures do |photo| %>
    <p>
      <%= photo.label :image %>
      <%= photo.file_field :image %>
      <%= photo.link_to_remove "Remove this image" %>
    </p>
  <%end%>
  <p>
  	<%= f.label :price %>
  	<%= f.text_field :price %>
  </p>
  <p>
  <%= f.label :description%>
    <%= f.text_area :description , :cols => "50", :rows => "5"%>
</p>
<p><%= f.link_to_add "Add a image", :pictures %></p>
  <p>
  	<%= f.submit %>
  </p>
<% end %>
</div>

app/views/admin/products/_form.html.erb
<div style = "margin-left:150px">
<%= nested_form_for([@category,@product], :url => admin_products_url, :html => {:multiple => true}) do |f|%>
  <ul>
  	<% @product.errors.full_messages.each do |error|%>
  	  <%= error %>
  	<% end %>
  </ul>

  <p>
    <%= f.label :category %>
    <%= f.select :category_id , options_for_select(@categories.map{|c| [c.name , c.id]})  %>
  </p>

  <p class="tag">
    <%= f.label :product_name %>
    <%= f.text_field :product_name %>
  </p>

  <%= f.fields_for :pictures do |photo| %>
    <p>
    	<%= photo.label :image %>
    	<%= photo.file_field :image %>
      <%= photo.link_to_remove "Remove this image", :class => "btn btn-success" %>
    </p>
    
  <%end%>
  <p>
  	<%= f.label :price %>
  	<%= f.text_field :price %>
  </p>
  <p>
  <%= f.label :description%>
    <%= f.text_area :description , :cols => "50", :rows => "5"%>
</p>
<p><%= f.link_to_add "Add a image", :pictures, :class => 'btn btn-primary' %></p>
  <p>
  	<%= f.submit %>
  </p>
<% end %>
</div>

app/views/admin/products/edit.html.erb
<h1>Edit Product</h1>
<%= render partial: 'edit_form'%>

app/views/admin/products/edit.js.erb
$('#edit_form').html("<%= escape_javascript(render :partial => 'edit_form') %>");

app/views/admin/products/index.html.erb
<div style="float: right;">
	<div style = "margin-right:20px">
		<%= form_tag admin_products_path, :method => 'get' do %>
			<div style = "margin-left:15px;">
			  <p>
			    <%= text_field_tag :search, params[:search], :placeholder => "search products" %>
			  </p>
	  		</div>
		<% end %>
	</div>
</div>
<div style = "margin-left:150px">
<h2><i><u><font color="#800000">List of Products :-</font></u></i></h2>		
	<table cellspacing="10">
		<tr>
			<% @products.each_with_index do |product,index| %>
				<% if (index%3) == 0 %>
					</tr>
					<tr>
		    	<% end %>
					<td style = "border: 1px solid black; padding: 50px;">
						<div><font color="#800000"><%= (product.product_name)%></font></div><br/>
					    <% product.pictures.each do |pik| %>
							<div style = "width:100px">
								<%= link_to image_tag(pik.image.url(:small)), admin_product_path(product) %>
							</div>
						<% end %>
						<div><font color="#JJ2350"><%= "Price: #{product.price}"%></font></div>
						<div><%= truncate(product.description, :length => 20, :separator => '...')%></div>
						<div><%= link_to 'Destroy', admin_product_path(product), :confirm => 'Are you sure?',:method => :delete, :class => 'btn btn-mini btn-danger' %>&nbsp;&nbsp;
						<%= link_to "Edit", edit_admin_product_path(product),:remote => true, :class => 'btn btn-mini' %></div>
					</td>
			<%end%>
		</tr>
	</table><br/>
	<div style = "margin-left:250px">
	<%= button_to "Add Products", new_admin_product_path, :id => "open-contacts-dialog-btn",
      :class => "inbox-sf-add-btn tip", :method => :get, :class => 'btn btn-primary' %>
</div>
	<%= will_paginate @products %>
</div>

<br/>

<div id='edit_form'>  </div>

app/views/admin/products/new.html.erb
<%= render partial: 'form'%>

app/views/admin/products/show.html.erb
<div style = "margin-left:20px">
	<% @product.pictures.each do |photo| %>
		<%= image_tag photo.image.url(:large) %>
	<%end%>
	
	<p>
	  <b>Price:</b>
	  <%= @product.price %>
	</p>
	<p>
		<b>Description:</b>
		<%= @product.description %>
	</p>
</div>