config/routes.rb
CISShoppingCart::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
    
  root :to => "homes#index"
  resources :products, :only => [:index, :show]
  resources :categories, :only => [:index, :show]
  resources :carts, :only => [:show]
  resources :homes, :only => [:index]
  resources :orders
  resources :profiles, :only => [:show]
  namespace :admin do
    root :to => 'dashboards#index'
    resources :dashboards , :only => [:index]
    resources :products, :categories 
    resources  :users ,:only => [:index]  do
      collection do
          post 'block_users'
       end
    end
  end 
  
  

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  has_many :products, :dependent => :destroy
  validates :name, :presence => true
  validates_uniqueness_of :name, :message => '%{value} has already been taken'

  has_many :sub_categories , :dependent => :destroy, :class_name => "Category", :foreign_key => "parent_id" 
  belongs_to :parent, :class_name => "Category"

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
	# before_filter :authenticate_admin
	layout 'admin'
	def index
		@categories = Category.where(parent_id: nil).paginate(:page => params[:page], :per_page => 2).search(params[:search])
	end
	def new
		@category = Category.new
		@categories = Category.where(parent_id: nil)
	end
	def show
		@category = Category.find(params[:id])
	end
	def edit
		@category = Category.find(params[:id])
		@categories = Category.where(parent_id: nil)
	end
	def create
		@category = Category.new(params[:category])
		@categories = Category.where(parent_id: nil)
		if @category.save
		  redirect_to admin_category_path(@category)
		else
		  render :new
		end 
	end
	def update
		@category = Category.find(params[:id])
		@category.update_attributes(params[:category])
		redirect_to admin_category_path(@category)
	end
	def destroy
		@category = Category.find(params[:id])
		if @category.delete
			redirect_to :action => 'index'
		else
			render 'index'
		end
	end
	def count
		@categories = Product.all
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.where(parent_id: nil).paginate(:page => params[:page], :per_page => 2).search(params[:search])
	end
	def show
		@category = Category.find(params[:id])
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div style="float: right;">
  <div style = "margin-right:20px">
    <%= form_tag categories_path, :method => 'get' do %>
      <div style = "margin-left:15px;">
        <p>
          <%= text_field_tag :search, params[:search], :placeholder => "search category" %>
        </p>
        </div>
    <% end %>
  </div>
</div>
<div style = "margin-left:50px;">
  <font color="#800000"><b>List Of Categories</b></font>
<% @categories.each do |category|%>
    <ul>
      <li>
        <p><%= link_to "#{category.name}", category_path(category) %>
      <ul>
      <% category.sub_categories.each do |sub_category| %>    
        <li>
          <p><%= link_to "#{sub_category.name}", category_path(sub_category)%> 
        </li>
      <%end%>
      </ul>
    </ul>
  <% end %>
  <%= will_paginate @categories%>
</div>

app/views/categories/show.html.erb
<div style = "margin-left:20px">
	<table>
		<tr>
			<div><font color="#800000"><%= "Category Name: #{@category.name}"%></font></div><br/>
			<% @category.products.each_with_index do |product,index| %>
				<% if (index%3) == 0 %>
		    	<% end %>
				<td style = "border: 1px solid black; padding: 50px;">
					<div><font color="#800000"><%= "Product_name: #{product.product_name}"%></font></div><br/>
					<% product.pictures.each do |photo| %>
						<div style = "width:100px">
							<%= link_to image_tag(photo.image(:large)), product_path(product) %>
						</div>
					<%end%>
	            	<%= product.description%>
					<%= product.price%>
				</td>
			<%end%>
			<h3>Number of Products{<%= @category.products.count %>}</h3>
		</tr>
		<tr>
			<% @category.sub_categories.each_with_index do |sub_category,index|%>
				<% sub_category.products.each do |product| %>
					<% if (index%4) == 0%>
					<%end%>
						<td style = "border: 1px solid black; padding: 50px;">
							<div><font color="#800000"><%= "Product_name: #{product.product_name}"%></font></div><br/>
							<% product.pictures.each do |photo| %>
								<div style = "width:100px">
									<%= link_to image_tag(photo.image.url(:large)), product_path(product) %>
								</div>
							<%end%>
			            	<%= product.description%>
							<%= product.price%>
						</td>
				<%end%>
			<%end%>	
		</tr>
	</table>
</div>