config/routes.rb
CISShoppingCart::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)
    
  root :to => "homes#index"
  resources :products, :only => [:index, :show]
  resources :categories, :only => [:index, :show]
  resources :carts, :only => [:show]
  resources :homes, :only => [:index]
  resources :orders
  resources :profiles, :only => [:show]
  namespace :admin do
    root :to => 'dashboards#index'
    resources :dashboards , :only => [:index]
    resources :products, :categories 
    resources  :users ,:only => [:index]  do
      collection do
          post 'block_users'
       end
    end
  end 
  
  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :parent_id
  has_many :products, :dependent => :destroy
  validates :name, :presence => true
  validates_uniqueness_of :name, :message => '%{value} has already been taken'

  has_many :sub_categories , :dependent => :destroy, :class_name => "Category", :foreign_key => "parent_id" 
  belongs_to :parent, :class_name => "Category"

  def self.search(search)
    if search
      find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
   attr_accessible :name, :email, :pay_type, :address, :address_latitude, :address_longitude, :address_locality, :address_country, :accepted_terms_and_conditions, :order_confirmation, :order_token

   has_and_belongs_to_many :products

   after_create :generate_token

   PAYMENT_TYPES = [ "Check" , "Credit card" , "Purchase order" ]

   validates_acceptance_of :accepted_terms_and_conditions

  def paypal_url(return_url)
    values = {
      :business => 'seller_1229899173_biz@railscasts.com',
      :cmd => '_order',
      :upload => 1,
      :return => return_url,
      :invoice => id
    }
    products.each_with_index do |product, index|
      values.merge!({
        "amount_#{index+1}" => product.price,
        "product_name_#{index+1}" => product.product_name
      })
    end
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end

  protected

  def generate_token
  	update_attributes!(:order_token => Digest::SHA1.hexdigest(id.to_s))
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
   attr_accessible :resource_id, :resource_type, :image, :image_file_name
   belongs_to :resource, :polymorphic => true

   validates_attachment_presence :image
   validates_attachment_size :image, :less_than => 5.megabytes
   validates_attachment_content_type :image, :content_type => ['image/jpeg', 'image/png']


	LARGE_IMAGE_SIZE = "300x300"
	SMALL_IMAGE_SIZE = "81x81"
	#MEDIUM_SMALL_IMAGE_SIZE = "180x84"
	SMALL_TINY_IMAGE_SIZE = "40x40"

	has_attached_file :image, 
      :path => ":rails_root/public/system/product/:id/:style/:filename",
      :url => "/system/product/:id/:style/:filename",
      :styles => { 
      :large => "#{LARGE_IMAGE_SIZE}",
      :small=> "#{SMALL_IMAGE_SIZE}>",
      #:medium=>"#{MEDIUM_IMAGE_SIZE}>",
      :small_tiny => "#{SMALL_TINY_IMAGE_SIZE}>"

    }
end

app/models/product.rb
class Product < ActiveRecord::Base
  attr_accessible :price, :description, :category_id, :product_name, :quantity, :pictures_attributes
  
  belongs_to :category

  has_and_belongs_to_many :orders

  has_many :pictures, :as => :resource, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true
  
  
  validates :price, :format => { :with => /^\d+??(?:\.\d{0,2})?$/ }, :numericality => {:greater_than => 0, :less_than => 100}
  validates :description, :presence => true
  validates :product_name, :presence => true
   

     
  def self.search(search)
    if search
      find(:all, :conditions => ['product_name LIKE ?', "%#{search}%"])
    else
      find(:all)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :pictures_attributes
  # attr_accessible :title, :body

  has_many :pictures, :as => :resource, :dependent => :destroy
  accepts_nested_attributes_for :pictures, :allow_destroy => true


  scope :admin_users, where(:admin => true)
  scope :users, where(:admin => false)

  
  def is_admin?
     return self.admin == true
  end	

  def banned?
    return self.blocked
  end

  def block_users_from_list(user_ids)
    users =  User.where("id in (?)" ,user_ids )
    users.each do |user|
      user.update_attribute(:blocked , true)
    end
  end  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
	before_filter :authenticate_user!
	def show
		@cart = Product.find(params[:id])
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		@categories = Category.where(parent_id: nil).paginate(:page => params[:page], :per_page => 2).search(params[:search])
	end
	def show
		@category = Category.find(params[:id])
	end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
	def index
		@products = Product.paginate(:page => params[:page], :per_page => 9).search(params[:search])
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	def new
		@order = Order.new
	end
	def show
		@order = Order.find(params[:id])
	end
	def edit
		@order = Order.find(params[:id])
	end
	def create
		@order = Order.new(params[:order])
		if @order.save
			redirect_to @order
		else
			render 'new'
		end
	end
	def update
		@order = Order.find(params[:id])
		if @order.update_attributes(params[:order])
			redirect_to order_path(@order)
		else
			render 'edit'
		end
	end
	def callback
	  @order   = Order.find(params[:id])
	  logger.debug params[:DR]
	  @notification = ActiveMerchant::Billing::Integrations::Ebs::Notification.new(params[:DR].to_s)
	  logger.debug "Success -- #{@notification.successful?}"
	  if @notification.successful?
	    render :action => 'success'
	  else
	    render :action => 'failure'
	  end
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		@products = Product.paginate(:page => params[:page], :per_page => 9)
	end
	def show
		@product = Product.find(params[:id])
	end
	# def new
	# 	@product = Product.new
	# end
	# def create
	# 	@product = Product.new(params[:product])
	# 	if @product.save
	# 		redirect_to @product
	# 	else
	# 		render 'index'
	# 	end
	# end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	def show
		@profile = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/owner_helper.rb
module OwnerHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/admin/shared/_left_panel.html.erb
<hr
<div style = "margin-left:50px">
	<ul>
		<li><%= link_to_unless_current "Users",  admin_users_path  %></li>
       	<li><%= link_to_unless_current "Categories",  admin_categories_path %></li>
        <li><%= link_to_unless_current "Products",  admin_products_path %></li>
	</ul>	
</div>
</hr>

app/views/layouts/admin.html.erb
<div style = "margin-left:50px">
<!DOCTYPE html>
<html>
<head>
  <title>CISShoppingCart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tags %>

</head>
<body style="background: #EEEEEE;">
  <div style = "float: right;margin-right: 23px;">
  <% if user_signed_in? %>  <%= current_user.email %> &nbsp; |

 <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary' %> 
<% else %> 
<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> 
<% end %> 
</div>
<div> <%= flash[:notice]%>
</div>
<div class='left'>
  <%= render :partial => 'admin/shared/left_panel'%>     
</div>

<div class='main_container'>
  <%= yield%>
</div>
</body>
</html>


<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
      </a>
      <h4><%= link_to "Admin Dashboard", admin_root_path, :class => 'btn btn-primary'%></h4>
      <div class="nav-collapse">
        <ul class="nav">
          
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<div style = "margin-left:50px">
<!DOCTYPE html>

<html>
<head>
  <title>CISShoppingCart</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag :defaults, "nested_form" %>
  <%= csrf_meta_tags %>

</head>
<body style="background: #EEEEEE;">
<div style = "float: right;margin-right: 23px;">
  <% if user_signed_in? %>  <%= current_user.email %> &nbsp; |
  <%= link_to "Profile", profile_path(current_user), :class => 'btn btn-primary'  if current_user%> &nbsp; |
  <%= link_to "Categories", categories_path, :class => 'btn btn-primary'%>&nbsp;|
 <%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => 'btn btn-primary' %> 
<% else %> 
<%= link_to "Sign up", new_user_registration_path %> or <%= link_to "sign in", new_user_session_path %> 
<% end %> 
</div>
<body>
<div style = "margin-left:20px">
	<h1>
	<form name="Form1">
	<input type="text" size="8" name="Clock"> </form>
	<script>
	function update()
	{
	var today=new Date();
	var hours=today.getHours();
	var minutes=today.getMinutes();
	var seconds=today.getSeconds();
	if (hours<10)
	hours="0"+hours;
	if (minutes<10)
	minutes="0"+minutes;
	if (seconds<10)
	seconds="0"+seconds;
	document.Form1.Clock.value=hours+":"+minutes+":"+seconds;
	setTimeout("update()",1000);
	}
	update();
	</script> 
	</h1>
</div>
<div> <%= flash[:notice]%>
</div>
<%= yield %>

</body>
</html>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
      </a>
      <h3><%= link_to "Home Page", root_path%></h3>
      <div class="nav-collapse">
        <ul class="nav">
          
        </ul>
      </div>
    </div>
  </div>
</div>